---
title: "Zutomayo Analysis"
format: html
---


```{r}
zutomayo <- read.csv("features2.csv", row.names=1)

head(zutomayo)


songcomparison <- read.csv("tripleanalysis.csv", row.names=1)

head(songcomparison)


emotion <- read.csv("tripleemotion.csv", row.names=1)
head(emotion)
```
```{r}
library(ggplot2)
library(tidyverse)
```



{r, fig.height=15, fig.width=10}



ggplot(zutomayo, aes(views, reorder(rownames(zutomayo), views))) +
  geom_col() + 
  ylab("")


```{r}
my_cols=rep("black", nrow(songcomparison))
my_cols[as.logical(songcomparison$artist)] = "green"
my_cols[as.logical(songcomparison$Zuttomayo)] = "purple"
my_cols[as.logical(songcomparison$artist_yorushika)] = "skyblue"


pca_input <- zutomayo %>%
  select(where(is.numeric))


comp_input <- songcomparison %>%
  select(where(is.numeric))



```


{r, fig.height=25, fig.width=25}
cij <- cor(songcomparison)

# install.packages("corrplot")
library(corrplot)

corrplot(cij)

```{r}
library(tidyverse)



pca <- prcomp(pca_input, scale=TRUE)
summary(pca)

compca <- prcomp(comp_input, scale=TRUE)
summary(compca)
```








```{r, fig.height=15, fig.width=15}

library(ggrepel)
p1 <- ggplot(pca$x, aes(PC1, PC2, label=row.names(pca$x))) +
  geom_point(size = 2, col=my_cols) + 
  geom_text_repel(size=3.3, max.overlaps = 7) + 
  labs(legend=zutomayo$artist)


p <- ggplot(compca$x, aes(PC1, PC2, label=row.names(compca$x))) +
  geom_point(size=2, col=my_cols) + 
  geom_text_repel(size=3.3, max.overlaps = 7) +
  labs(legend=songcomparison$artist)


library(plotly)

artist_label <- case_when(
  as.logical(songcomparison$Zuttomayo) ~ "Zutomayo", 
  as.logical(songcomparison$artist) ~ "Mrs. GREEN APPLE",
  as.logical(songcomparison$artist_yorushika) ~ "Yorushika",
  as.logical(songcomparison$EVE) ~ "Eve",
  TRUE ~ "Unknown")

plot_ly(as.data.frame(compca$x), x=~PC1, y=~PC2, z=~PC3, type = "scatter3d", mode="markers", color = artist_label,
  colors = c("Mrs. GREEN APPLE" = "green", "Zutomayo" = "purple"),
  marker = list(size = 4), text=row.names(compca$x), hoverinfo = "text")
  
```


```{r, fig.height=15, fig.width=15}
ggplot(compca$rotation) +
  aes(PC1, reorder(rownames(compca$rotation), PC1)) +
  geom_col()


ggplot(compca$rotation) +
  aes(PC2, reorder(rownames(compca$rotation), PC2)) +
  geom_col()

```



```{r}

pr.var <- pca$sdev^2
pve <- pr.var/(sum(pr.var))
plot(c(1, pve), xlab = "Principal Components", ylab="Proportion of Variance Explained", ylim= c(0, 1), type = "o")

# Alternative scree plot of the same data, note data driven y-axis
barplot(pve, ylab = "Percent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```



## Instrumental Analysis

```{r}
drop_patterns <- c("theme_", "emotion_", "lyrical_sentiment",
                    "views", "like_", "comment_", "year", 
                    "release_", "days_since", "yt_", "Spotify",
                    "Zuttomayo", "Mrs.Green", "key_numeric",
                    "key_mode", "duration_sec")

instrument_input <- songcomparison %>%
  select(where(is.numeric)) %>%
  select(-matches(paste(drop_patterns, collapse = "|")))

colnames(instrument_input)




inst_pca <- prcomp(instrument_input, center = TRUE, scale. = TRUE)


plot_ly(as.data.frame(inst_pca$x), x=~PC1, y=~PC2, z=~PC3, type = "scatter3d", mode="markers", color = artist_label,
  colors = c("Mrs. GREEN APPLE" = "green", "Zutomayo" = "purple", "Yorushika" = "skyblue"),
  marker = list(size = 4), text=row.names(inst_pca$x), hoverinfo = "text")


p_2d <- plot_ly(as.data.frame(inst_pca$x), x=~PC1, y=~PC2, type = "scatter", mode="markers", color = ~artist_label,
  colors = c("Mrs. GREEN APPLE" = "green", "Zutomayo" = "purple", "Yorushika" = "skyblue", "Eve" = "gray"),
  marker = list(size = 4), text= ~row.names(inst_pca$x), hoverinfo = "text") %>% layout(dragmode='zoom') %>%
  config(scrollZoom=TRUE)

ggplot(inst_pca$rotation) +
  aes(PC2, reorder(rownames(inst_pca$rotation), PC2)) +
  geom_col()

p_2d
```

PVE for instruments

```{r}

pr.var <- inst_pca$sdev^2
pve <- pr.var/(sum(pr.var))
plot(c(1, pve), xlab = "Principal Components", ylab="Proportion of Variance Explained", ylim= c(0, 1), type = "o")

# Alternative scree plot of the same data, note data driven y-axis
barplot(pve, ylab = "Percent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```



## PCA for thematic differences

```{r}

thematic_input <- emotion %>%
  select(where(is.numeric))

colnames(thematic_input)

## REdoing artist label
artist_label2 <- case_when(
  as.logical(emotion$Zuttomayo) ~ "Zutomayo", 
  as.logical(emotion$artist) ~ "Mrs. GREEN APPLE",
  as.logical(emotion$artist_yorushika) ~ "Yorushika",
  TRUE ~ "Unknown")


theme_pca <- prcomp(thematic_input, center = TRUE, scale. = TRUE)


plot_ly(as.data.frame(theme_pca$x), x=~PC1, y=~PC2, z=~PC3, type = "scatter3d", mode="markers", color = artist_label2,
  colors = c("Mrs. GREEN APPLE" = "green", "Zutomayo" = "purple", "Yorushika" = "skyblue"),
  marker = list(size = 4), text=row.names(theme_pca$x), hoverinfo = "text")


p_2d <- plot_ly(as.data.frame(theme_pca$x), x=~PC1, y=~PC2, type = "scatter", mode="markers", color = artist_label2,
  colors = c("Mrs. GREEN APPLE" = "green", "Zutomayo" = "purple", "Yorushika" = "skyblue"),
  marker = list(size = 4), text= ~row.names(theme_pca$x), hoverinfo = "text") %>% layout(dragmode='zoom') %>%
  config(scrollZoom=TRUE)


ggplot(theme_pca$rotation) +
  aes(PC1, reorder(rownames(theme_pca$rotation), PC1)) +
  geom_col()

ggplot(theme_pca$rotation) +
  aes(PC2, reorder(rownames(theme_pca$rotation), PC2)) +
  geom_col()

p_2d
```